code_signing:
  certificate: $CERTIFICATE
  certificate_password: $CERTIFICATE_PASSWORD
  provisioning_profile: $PROVISIONING_PROFILE

workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        XCODE_WORKSPACE: Runner.xcworkspace
        XCODE_SCHEME: Runner
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
          keychain add-certificates
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
