workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        CERTIFICATE: <cole aqui o conteúdo sem aspas>
        PROVISIONING_PROFILE: <idem>
        CERTIFICATE_PASSWORD: your_password
    scripts:
      - name: Decode signing files
        script: |
          echo "$CERTIFICATE" | base64 -d > certificate.p12
          echo "$PROVISIONING_PROFILE" | base64 -d > provisioning_profile.mobileprovision
      - name: Set up keychain
        script: |
          keychain initialize
          keychain add-certificates --certificate certificate.p12 --password $CERTIFICATE_PASSWORD
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
