# Podfile completo para Flutter com suporte a localização, câmera e Bluetooth no iOS

platform :ios, '11.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  # Permissões do plugin permission_handler
  pod 'Permission-LocationWhenInUse', :path => '../.symlinks/plugins/permission_handler/ios'
  pod 'Permission-Bluetooth', :path => '../.symlinks/plugins/permission_handler/ios'
  pod 'Permission-Camera', :path => '../.symlinks/plugins/permission_handler/ios'
end

# Pós-instalação para garantir definição das permissões
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_HANDLER_LOCATION=1',
        'PERMISSION_HANDLER_CAMERA=1',
        'PERMISSION_HANDLER_BLUETOOTH=1'
      ]
    end
  end
end
